import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { parse } from '@babel/parser';

const slash = (value) => value.replaceAll('\\', '/');

function typeEntries(value, label = '.', entries = []) {
  if (!value || typeof value !== 'object') return entries;
  for (const [key, child] of Object.entries(value)) {
    if (key === 'types' && typeof child === 'string') entries.push([label, child]);
    else if (typeof child === 'object') typeEntries(child, key.startsWith('.') ? key : label, entries);
  }
  return entries;
}

// Public return types can expose local modules without naming them in index.d.ts.
export async function snapshotPackageApi(packageRoot) {
  const root = path.resolve(packageRoot);
  const manifest = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  const entries = typeEntries(manifest.exports);
  if (manifest.types) entries.push(['package.types', manifest.types]);
  if (!entries.length) throw new Error(`No public type entry points in ${manifest.name}.`);
  entries.sort(([a, ap], [b, bp]) => a.localeCompare(b) || ap.localeCompare(bp));
  const files = new Map();

  async function visit(relativePath) {
    const absolute = path.resolve(root, relativePath);
    const relative = slash(path.relative(root, absolute));
    if (relative.startsWith('../') || path.isAbsolute(relative)) {
      throw new Error(`Declaration escapes package: ${relativePath}`);
    }
    if (files.has(relative)) return;
    const raw = await readFile(absolute, 'utf8');
    const source = raw.replaceAll('\r\n', '\n').replace(/^\/\/[#@] sourceMappingURL=.*\n?/gm, '').trimEnd() + '\n';
    files.set(relative, source);
    const tree = parse(source, { sourceType: 'module', plugins: [['typescript', { dts: true }]] });
    const references = new Set();
    function walk(node) {
      if (!node || typeof node !== 'object') return;
      if (['ImportDeclaration', 'ExportNamedDeclaration', 'ExportAllDeclaration'].includes(node.type) && node.source) references.add(node.source.value);
      if (node.type === 'TSImportType' && node.argument?.type === 'StringLiteral') references.add(node.argument.value);
      if (node.type === 'TSExternalModuleReference' && node.expression?.type === 'StringLiteral') references.add(node.expression.value);
      for (const [key, value] of Object.entries(node)) {
        if (['loc', 'comments', 'leadingComments', 'trailingComments', 'tokens'].includes(key)) continue;
        if (Array.isArray(value)) value.forEach(walk);
        else if (value && typeof value === 'object') walk(value);
      }
    }
    walk(tree.program);
    for (const comment of tree.comments ?? []) {
      const match = comment.value.match(/^\/\s*<reference\s+path=["']([^"']+)["']/);
      if (match) references.add(match[1].startsWith('.') ? match[1] : `./${match[1]}`);
    }
    for (const fileName of references) {
      if (!fileName.startsWith('.')) continue;
      let target = path.resolve(path.dirname(absolute), fileName);
      if (!/\.d\.(?:ts|mts|cts)$/.test(target)) {
        if (/\.mjs$/.test(target)) target = target.replace(/\.mjs$/, '.d.mts');
        else if (/\.cjs$/.test(target)) target = target.replace(/\.cjs$/, '.d.cts');
        else target = target.replace(/\.(?:js|ts)$/, '') + '.d.ts';
      }
      await visit(path.relative(root, target));
    }
  }

  for (const [, entry] of entries) await visit(entry);
  return [
    `// Public declaration graph for ${manifest.name}. Generated by pnpm api:update.`,
    '// Review artifact; file sections retain their original module boundaries.',
    ...entries.map(([label, entry]) => `// Entry ${label}: ${entry}`),
    '',
    ...[...files].sort(([a], [b]) => a.localeCompare(b)).map(([file, source]) => `// File: ${file}\n${source}`)
  ].join('\n');
}
