// Public declaration graph for @visual-html/core. Generated by pnpm api:update.
// Review artifact; file sections retain their original module boundaries.
// Entry .: ./dist/index.d.ts
// Entry ./profiles/email: ./dist/profiles.d.ts
// Entry ./profiles/slides: ./dist/profiles.d.ts
// Entry ./profiles/web: ./dist/profiles.d.ts
// Entry package.types: ./dist/index.d.ts

// File: dist/controller.d.ts
import type { CommandResult, EditorCommand, EditorEventMap, EditorEventType, EditorProfile, EditorSnapshot, ExportResult, ParsedNode, ReplaceSourceOptions, SourceReplacementResult } from './types.js';
export interface CreateEditorControllerOptions {
    html: string;
    profile: EditorProfile;
}
export declare class EditorController {
    readonly id: string;
    private workspace;
    private index;
    private profile;
    private history;
    private historyCursor;
    private checkpoint;
    private keyCounter;
    private listeners;
    private eventListeners;
    private constructor();
    static create(options: CreateEditorControllerOptions): Promise<EditorController>;
    private allocateKey;
    private parse;
    private parseWorkspace;
    private emit;
    private emitEvent;
    private captureState;
    private isDirty;
    private publishObservableChanges;
    private publishTransaction;
    private rejectTransaction;
    private applyPatches;
    subscribe(listener: () => void): () => void;
    on<K extends EditorEventType>(type: K, listener: (event: EditorEventMap[K]) => void): () => void;
    getSnapshot(): EditorSnapshot;
    getNode(key: string): ParsedNode | undefined;
    setProfile(profile: EditorProfile): void;
    createCheckpoint(): void;
    dispatch(command: EditorCommand, baseRevision?: number): Promise<CommandResult>;
    undo(): Promise<CommandResult>;
    redo(): Promise<CommandResult>;
    replaceSource(html: string, options?: ReplaceSourceOptions): Promise<SourceReplacementResult>;
    export(): Promise<ExportResult>;
}

// File: dist/index.d.ts
export { EditorController } from './controller.js';
export type { CreateEditorControllerOptions } from './controller.js';
export { defineEditorProfile, editorProfiles, emailProfile, extendEditorProfile, slidesProfile, webProfile } from './profiles.js';
export { RUNTIME_NODE_ATTRIBUTE } from './projection.js';
export { hardenRuntimeHtml, RUNTIME_CONTENT_SECURITY_POLICY } from './runtime-security.js';
export { RichTextRangeError, toggleInlineMarkInHtml } from './rich-text.js';
export type { InlineMarkTransform } from './rich-text.js';
export type { AspectRatioOption, CommandFailure, CommandResult, CommandSuccess, DocumentIndex, EditorCapabilities, EditorCommand, EditorEvent, EditorEventBase, EditorEventMap, EditorEventType, EditorProfile, EditorProfileOverrides, EditorSnapshot, EditorTransactionKind, ExternalSourceUpdatePolicy, ExportResult, FatalErrorEvent, FileId, HtmlPolicy, InlineMark, NodeKey, ParsedAttribute, ParsedNode, RuntimeProjection, ReplaceSourceOptions, RevisionChangedEvent, SourceFile, SourcePatch, SourceReplacementResult, SourceReplacementSuccess, SourceRange, TextRange, TransactionCommittedEvent, TransactionRejectedEvent, DirtyChangedEvent, ProfileChangedEvent, ValidationChangedEvent, ValidationIssue, WorkspaceSnapshot } from './types.js';

// File: dist/profiles.d.ts
import type { EditorProfile, EditorProfileOverrides } from './types.js';
export declare function defineEditorProfile(profile: EditorProfile): EditorProfile;
export declare function extendEditorProfile(base: EditorProfile, overrides: EditorProfileOverrides): EditorProfile;
export declare const webProfile: EditorProfile;
export declare const slidesProfile: EditorProfile;
export declare const emailProfile: EditorProfile;
export declare const editorProfiles: {
    email: EditorProfile;
    slides: EditorProfile;
    web: EditorProfile;
};

// File: dist/projection.d.ts
import type { DocumentIndex, RuntimeProjection } from './types.js';
export declare const RUNTIME_NODE_ATTRIBUTE = "data-vhe-node";
export declare function buildRuntimeProjection(source: string, index: DocumentIndex): RuntimeProjection;

// File: dist/rich-text.d.ts
import type { InlineMark, TextRange } from './types.js';
export interface RichTextSourceEdit {
    start: number;
    end: number;
    replacement: string;
}
export interface InlineMarkTransform {
    html: string;
    active: boolean;
    action: 'add' | 'remove';
}
export declare class RichTextRangeError extends Error {
    constructor(message: string);
}
export declare function isInlineMarkTag(tagName: string, mark: InlineMark): boolean;
export declare function richTextSourceEdits(source: string, edited: string): RichTextSourceEdit[] | null;
export declare function toggleInlineMarkInHtml(source: string, range: TextRange, mark: InlineMark): InlineMarkTransform;

// File: dist/runtime-security.d.ts
export declare const RUNTIME_CONTENT_SECURITY_POLICY: string;
/**
 * Builds an inert browser preview from an untrusted runtime projection.
 * Canonical source is never changed; normalization only affects the iframe copy.
 */
export declare function hardenRuntimeHtml(source: string): string;

// File: dist/types.d.ts
export type FileId = string;
export type NodeKey = string;
export interface SourceRange {
    start: number;
    end: number;
}
export interface TextRange {
    start: number;
    end: number;
}
export type InlineMark = 'strong' | 'em' | 'u' | 's';
export interface SourceFile {
    id: FileId;
    path: string;
    mediaType: string;
    content: string;
    contentHash: string;
}
export interface WorkspaceSnapshot {
    revision: number;
    entryFileId: FileId;
    files: ReadonlyMap<FileId, SourceFile>;
}
export interface AspectRatioOption {
    id: string;
    label: string;
    width: number;
    height: number;
}
export interface HtmlPolicy {
    allowedTags: readonly string[];
    allowedAttributes: readonly string[];
    allowedCssProperties: readonly string[];
    allowedProtocols: readonly string[];
    allowDataAttributes: boolean;
    allowAriaAttributes: boolean;
}
export interface EditorCapabilities {
    editText: boolean;
    editStyles: boolean;
    insertImages: boolean;
    replaceImages: boolean;
    dragElements: boolean;
    resizeElements: boolean;
    duplicateElements: boolean;
    deleteElements: boolean;
    importHtml: boolean;
    editSource: boolean;
}
export interface EditorProfile {
    id: 'email' | 'slides' | 'web' | string;
    label: string;
    description: string;
    html: HtmlPolicy;
    capabilities: EditorCapabilities;
    aspectRatios: readonly AspectRatioOption[];
    defaultAspectRatioId: string;
    fidelity: 'preserve' | 'balanced' | 'normalize';
}
export interface EditorProfileOverrides {
    id?: string;
    label?: string;
    description?: string;
    html?: Partial<HtmlPolicy>;
    capabilities?: Partial<EditorCapabilities>;
    aspectRatios?: readonly AspectRatioOption[];
    defaultAspectRatioId?: string;
    fidelity?: EditorProfile['fidelity'];
}
export interface ParsedAttribute {
    name: string;
    value: string;
    range?: SourceRange;
}
export interface ParsedNode {
    key: NodeKey;
    revision: number;
    fileId: FileId;
    tagName: string;
    range?: SourceRange;
    startTagRange?: SourceRange;
    endTagRange?: SourceRange;
    innerRange?: SourceRange;
    attributes: ReadonlyMap<string, ParsedAttribute>;
    parentKey?: NodeKey;
    childKeys: readonly NodeKey[];
    hasElementChildren: boolean;
    textContent: string;
    virtual: boolean;
}
export interface DocumentIndex {
    revision: number;
    isFragment: boolean;
    nodes: ReadonlyMap<NodeKey, ParsedNode>;
    rootKeys: readonly NodeKey[];
}
export interface SourcePatch {
    fileId: FileId;
    start: number;
    end: number;
    expectedHash: string;
    replacement: string;
}
export type EditorCommand = {
    type: 'setText';
    nodeKey: NodeKey;
    text: string;
} | {
    type: 'setRichText';
    nodeKey: NodeKey;
    html: string;
} | {
    type: 'toggleInlineMark';
    nodeKey: NodeKey;
    range: TextRange;
    mark: InlineMark;
} | {
    type: 'setAttribute';
    nodeKey: NodeKey;
    name: string;
    value: string | null;
} | {
    type: 'setStyle';
    nodeKey: NodeKey;
    property: string;
    value: string | null;
} | {
    type: 'setStyles';
    nodeKey: NodeKey;
    styles: Readonly<Record<string, string | null>>;
} | {
    type: 'removeNode';
    nodeKey: NodeKey;
} | {
    type: 'duplicateNode';
    nodeKey: NodeKey;
} | {
    type: 'insertImage';
    targetNodeKey?: NodeKey;
    src: string;
    alt: string;
} | {
    type: 'replaceImage';
    nodeKey: NodeKey;
    src: string | null;
    alt?: string;
} | {
    type: 'applySource';
    source: string;
};
export interface ValidationIssue {
    code: string;
    severity: 'info' | 'warning' | 'error' | 'blocking';
    message: string;
    fileId?: FileId;
    nodeKey?: NodeKey;
    range?: SourceRange;
}
export interface RuntimeProjection {
    revision: number;
    html: string;
    runtimeAttribute: string;
}
export interface EditorSnapshot {
    revision: number;
    html: string;
    profile: EditorProfile;
    nodes: readonly ParsedNode[];
    issues: readonly ValidationIssue[];
    projection: RuntimeProjection;
    canUndo: boolean;
    canRedo: boolean;
    dirty: boolean;
}
export interface CommandSuccess {
    ok: true;
    revision: number;
    description: string;
}
export interface CommandFailure {
    ok: false;
    code: string;
    message: string;
}
export type CommandResult = CommandSuccess | CommandFailure;
export type ExternalSourceUpdatePolicy = 'replace' | 'replace-when-clean' | 'reject-when-dirty';
export interface ReplaceSourceOptions {
    policy?: ExternalSourceUpdatePolicy;
    createCheckpoint?: boolean;
    recordHistory?: boolean;
    description?: string;
}
export interface SourceReplacementSuccess extends CommandSuccess {
    replaced: boolean;
    reason?: 'unchanged' | 'dirty';
}
export type SourceReplacementResult = SourceReplacementSuccess | CommandFailure;
export type EditorTransactionKind = 'command' | 'undo' | 'redo' | 'source-replacement';
export interface EditorEventBase {
    controllerId: string;
    revision: number;
}
export interface TransactionCommittedEvent extends EditorEventBase {
    type: 'transactionCommitted';
    kind: EditorTransactionKind;
    previousRevision: number;
    description: string;
    command?: EditorCommand;
    patches: readonly SourcePatch[];
}
export interface TransactionRejectedEvent extends EditorEventBase {
    type: 'transactionRejected';
    kind: 'command' | 'source-replacement';
    command?: EditorCommand;
    result: CommandFailure;
}
export interface RevisionChangedEvent extends EditorEventBase {
    type: 'revisionChanged';
    previousRevision: number;
    kind: EditorTransactionKind;
    description: string;
}
export interface ValidationChangedEvent extends EditorEventBase {
    type: 'validationChanged';
    issues: readonly ValidationIssue[];
}
export interface DirtyChangedEvent extends EditorEventBase {
    type: 'dirtyChanged';
    dirty: boolean;
}
export interface ProfileChangedEvent extends EditorEventBase {
    type: 'profileChanged';
    profile: EditorProfile;
    previousProfile: EditorProfile;
}
export interface FatalErrorEvent extends EditorEventBase {
    type: 'fatalError';
    error: Error;
}
export interface EditorEventMap {
    transactionCommitted: TransactionCommittedEvent;
    transactionRejected: TransactionRejectedEvent;
    revisionChanged: RevisionChangedEvent;
    validationChanged: ValidationChangedEvent;
    dirtyChanged: DirtyChangedEvent;
    profileChanged: ProfileChangedEvent;
    fatalError: FatalErrorEvent;
}
export type EditorEventType = keyof EditorEventMap;
export type EditorEvent = EditorEventMap[EditorEventType];
export interface ExportResult {
    revision: number;
    html: string;
    issues: readonly ValidationIssue[];
}
