// Public declaration graph for @visual-html/deck. Generated by pnpm api:update.
// Review artifact; file sections retain their original module boundaries.
// Entry .: ./dist/index.d.ts
// Entry ./adapters/claude-design: ./dist/claude-design.d.ts
// Entry package.types: ./dist/index.d.ts

// File: dist/claude-design.d.ts
import type { ClaudeDesignImportResult, HtmlDeck } from './types.js';
export declare function isClaudeDesignDeck(source: string): boolean;
export declare function importClaudeDesignDeck(source: string): ClaudeDesignImportResult;
export declare function exportClaudeDesignDeck(deckInput: HtmlDeck): string;

// File: dist/controller.d.ts
import type { AddSlideOptions, CreateDeckControllerOptions, DeckCommandResult, DeckSnapshot, HtmlDeck, HtmlDeckSlide, ReplaceDeckOptions, SlideId, UpdateSlideOptions } from './types.js';
export declare class DeckController {
    private deck;
    private activeSlideId;
    private revision;
    private currentContent;
    private checkpointContent;
    private idCounter;
    private history;
    private historyCursor;
    private snapshot;
    private listeners;
    private constructor();
    static create(options: CreateDeckControllerOptions): Promise<DeckController>;
    subscribe(listener: () => void): () => void;
    private emit;
    private touch;
    private success;
    private failure;
    private record;
    private allocateSlideId;
    private insertSlide;
    private takeSlide;
    getSnapshot(): DeckSnapshot;
    setActiveSlide(slideId: SlideId): DeckCommandResult;
    addSlide(options?: AddSlideOptions): DeckCommandResult;
    duplicateSlide(slideId: SlideId): DeckCommandResult;
    removeSlide(slideId: SlideId): DeckCommandResult;
    moveSlide(slideId: SlideId, toIndex: number): DeckCommandResult;
    updateSlide(slideId: SlideId, patch: Partial<Omit<HtmlDeckSlide, 'id'>>, options?: UpdateSlideOptions): DeckCommandResult;
    replaceDeck(deckInput: HtmlDeck, options?: ReplaceDeckOptions): DeckCommandResult;
    createCheckpoint(): void;
    undo(): DeckCommandResult;
    redo(): DeckCommandResult;
    export(): HtmlDeck;
}

// File: dist/index.d.ts
export { DeckController } from './controller.js';
export { cloneSlide, createBlankSlideHtml, normalizeDeck, parseDeck, serializeDeck } from './serialization.js';
export { exportClaudeDesignDeck, importClaudeDesignDeck, isClaudeDesignDeck } from './claude-design.js';
export type { AddSlideOptions, ClaudeDesignImportResult, ClaudeDesignImportWarning, CreateDeckControllerOptions, DeckCommandFailure, DeckCommandResult, DeckCommandSuccess, DeckId, DeckSnapshot, HtmlDeck, HtmlDeckSlide, ReplaceDeckOptions, SlideId, UpdateSlideOptions } from './types.js';

// File: dist/serialization.d.ts
import type { HtmlDeck, HtmlDeckSlide } from './types.js';
export declare function cloneSlide(slide: HtmlDeckSlide): HtmlDeckSlide;
export declare function normalizeDeck(deck: HtmlDeck): HtmlDeck;
export declare function createBlankSlideHtml(width: number, height: number, title?: string): string;
export declare function serializeDeck(deck: HtmlDeck, space?: number): string;
export declare function parseDeck(source: string): HtmlDeck;

// File: dist/types.d.ts
export type DeckId = string;
export type SlideId = string;
export interface HtmlDeckSlide {
    id: SlideId;
    html: string;
    title?: string;
    label?: string;
    notes?: string;
    metadata?: Readonly<Record<string, unknown>>;
}
export interface HtmlDeck {
    schema: 'visual-html-deck';
    version: 1;
    id: DeckId;
    title?: string;
    width: number;
    height: number;
    slides: readonly HtmlDeckSlide[];
    themeCss?: string;
    metadata?: Readonly<Record<string, unknown>>;
}
export interface DeckSnapshot {
    revision: number;
    deck: HtmlDeck;
    activeSlideId: SlideId;
    activeSlideIndex: number;
    canUndo: boolean;
    canRedo: boolean;
    dirty: boolean;
}
export interface DeckCommandSuccess {
    ok: true;
    revision: number;
    description: string;
    slideId?: SlideId;
}
export interface DeckCommandFailure {
    ok: false;
    code: string;
    message: string;
}
export type DeckCommandResult = DeckCommandSuccess | DeckCommandFailure;
export interface CreateDeckControllerOptions {
    deck: HtmlDeck;
    activeSlideId?: SlideId;
}
export interface AddSlideOptions {
    afterSlideId?: SlideId;
    slide?: Partial<Omit<HtmlDeckSlide, 'id'>> & {
        id?: SlideId;
    };
}
export interface UpdateSlideOptions {
    recordHistory?: boolean;
    description?: string;
}
export interface ReplaceDeckOptions {
    activeSlideId?: SlideId;
    recordHistory?: boolean;
    description?: string;
}
export interface ClaudeDesignImportWarning {
    code: string;
    message: string;
}
export interface ClaudeDesignImportResult {
    deck: HtmlDeck;
    warnings: readonly ClaudeDesignImportWarning[];
}
