// Public declaration graph for @visual-html/react. Generated by pnpm api:update.
// Review artifact; file sections retain their original module boundaries.
// Entry .: ./dist/index.d.ts
// Entry ./styles.css: ./styles.css.d.ts
// Entry package.types: ./dist/index.d.ts

// File: dist/deck-navigator.d.ts
import React from 'react';
import type { DeckController, SlideId } from '@visual-html/deck';
export interface DeckNavigatorProps {
    controller: DeckController;
    className?: string;
    onSlideChange?: (slideId: SlideId) => void;
    onHistoryChange?: () => void;
}
export declare function DeckNavigator({ controller, className, onSlideChange, onHistoryChange }: DeckNavigatorProps): React.JSX.Element;

// File: dist/editor-types.d.ts
import type React from 'react';
import type { EditorController, NodeKey, ParsedNode } from '@visual-html/core';
import type { ElementBehaviorResolver } from './element-behavior.js';
export interface ResolvedAsset {
    url: string;
    alt?: string;
}
export interface AssetAdapter {
    upload(file: File): Promise<ResolvedAsset>;
}
export interface EditorSelectionChange {
    nodeKey: NodeKey | null;
    node?: ParsedNode;
}
export interface HtmlImportInput {
    file: File;
    html: string;
}
export interface HtmlImportPreview {
    title?: string;
    description?: string;
    warnings?: readonly string[];
    hasUnsavedChanges?: boolean;
}
export interface HtmlImportResult {
    message?: string;
}
export interface HtmlImportAdapter {
    accept?: string;
    maxBytes?: number;
    prepare?: (input: HtmlImportInput) => HtmlImportPreview | Promise<HtmlImportPreview>;
    apply: (input: HtmlImportInput) => void | HtmlImportResult | Promise<void | HtmlImportResult>;
}
export interface VisualHtmlEditorProps {
    controller: EditorController;
    assetAdapter?: AssetAdapter;
    className?: string;
    brandHref?: string;
    documentTitle?: string;
    toolbarContent?: React.ReactNode;
    navigationRail?: React.ReactNode;
    /** Additional unsaved workspace changes, such as deck structure or another slide. */
    workspaceDirty?: boolean;
    sidebarHeader?: React.ReactNode;
    importAdapter?: HtmlImportAdapter;
    elementBehaviorResolvers?: readonly ElementBehaviorResolver[];
    onSelectionChange?: (selection: EditorSelectionChange) => void;
    onExport?: (html: string) => void;
    onExportRequest?: () => void | Promise<void>;
}

// File: dist/element-behavior.d.ts
import type { NodeKey, ParsedNode } from '@visual-html/core';
export type ElementEditTarget = 'self' | 'nearest-rich-text-region';
export interface ElementBehavior {
    kind: string;
    editTarget: ElementEditTarget;
}
export interface ElementBehaviorContext {
    node: ParsedNode;
    nodes: ReadonlyMap<NodeKey, ParsedNode>;
}
export type ElementBehaviorResolver = (context: ElementBehaviorContext) => Partial<ElementBehavior> | undefined;
export declare function resolveElementBehavior(node: ParsedNode, nodes: ReadonlyMap<NodeKey, ParsedNode>, resolvers?: readonly ElementBehaviorResolver[]): ElementBehavior;

// File: dist/html-editor.d.ts
import React from 'react';
import type { EditorController, EditorProfile, ExternalSourceUpdatePolicy, SourceReplacementResult, ValidationIssue } from '@visual-html/core';
import { type HtmlEditorChange } from './use-html-editor.js';
import { type VisualHtmlEditorProps } from './visual-html-editor.js';
export interface HtmlEditorProps extends Omit<VisualHtmlEditorProps, 'controller'> {
    value: string;
    profile: EditorProfile;
    externalUpdate?: ExternalSourceUpdatePolicy;
    onChange?: (change: HtmlEditorChange) => void;
    onValidationChange?: (issues: readonly ValidationIssue[]) => void;
    onDirtyChange?: (dirty: boolean) => void;
    onReady?: (controller: EditorController) => void;
    onExternalUpdateResult?: (result: SourceReplacementResult) => void;
    onError?: (error: Error) => void;
    loadingFallback?: React.ReactNode;
    errorFallback?: React.ReactNode | ((error: Error) => React.ReactNode);
}
export declare function HtmlEditor({ value, profile, externalUpdate, onChange, onValidationChange, onDirtyChange, onReady, onExternalUpdateResult, onError, loadingFallback, errorFallback, ...editorProps }: HtmlEditorProps): React.JSX.Element;

// File: dist/index.d.ts
export { DeckNavigator } from './deck-navigator.js';
export { resolveElementBehavior } from './element-behavior.js';
export { HtmlEditor } from './html-editor.js';
export { VisualHtmlEditor } from './visual-html-editor.js';
export { useDeckSnapshot } from './use-deck-snapshot.js';
export { useEditorSnapshot } from './use-editor-snapshot.js';
export { useHtmlEditor } from './use-html-editor.js';
export type { DeckNavigatorProps } from './deck-navigator.js';
export type { ElementBehavior, ElementBehaviorContext, ElementBehaviorResolver, ElementEditTarget } from './element-behavior.js';
export type { HtmlEditorProps } from './html-editor.js';
export type { HtmlEditorChange, UseHtmlEditorOptions, UseHtmlEditorResult } from './use-html-editor.js';
export type { AssetAdapter, EditorSelectionChange, HtmlImportAdapter, HtmlImportInput, HtmlImportPreview, HtmlImportResult, ResolvedAsset, VisualHtmlEditorProps } from './visual-html-editor.js';

// File: dist/use-deck-snapshot.d.ts
import type { DeckController, DeckSnapshot } from '@visual-html/deck';
export declare function useDeckSnapshot(controller: DeckController): DeckSnapshot;

// File: dist/use-editor-snapshot.d.ts
import type { EditorController, EditorSnapshot } from '@visual-html/core';
export declare function useEditorSnapshot(controller: EditorController): EditorSnapshot;

// File: dist/use-html-editor.d.ts
import { EditorController, type EditorProfile, type ExternalSourceUpdatePolicy, type SourceReplacementResult, type TransactionCommittedEvent, type ValidationIssue } from '@visual-html/core';
export interface HtmlEditorChange {
    html: string;
    revision: number;
    transaction: TransactionCommittedEvent;
}
export interface UseHtmlEditorOptions {
    value: string;
    profile: EditorProfile;
    externalUpdate?: ExternalSourceUpdatePolicy;
    onChange?: (change: HtmlEditorChange) => void;
    onValidationChange?: (issues: readonly ValidationIssue[]) => void;
    onDirtyChange?: (dirty: boolean) => void;
    onReady?: (controller: EditorController) => void;
    onExternalUpdateResult?: (result: SourceReplacementResult) => void;
    onError?: (error: Error) => void;
}
export interface UseHtmlEditorResult {
    controller: EditorController | null;
    status: 'loading' | 'ready' | 'error';
    error: Error | null;
}
export declare function useHtmlEditor({ value, profile, externalUpdate, onChange, onValidationChange, onDirtyChange, onReady, onExternalUpdateResult, onError }: UseHtmlEditorOptions): UseHtmlEditorResult;

// File: dist/visual-html-editor.d.ts
import React from 'react';
import type { VisualHtmlEditorProps } from './editor-types.js';
export type { ResolvedAsset, AssetAdapter, EditorSelectionChange, HtmlImportInput, HtmlImportPreview, HtmlImportResult, HtmlImportAdapter, VisualHtmlEditorProps } from './editor-types.js';
export declare function VisualHtmlEditor({ controller, assetAdapter, className, brandHref, documentTitle, toolbarContent, navigationRail, workspaceDirty, sidebarHeader, importAdapter, elementBehaviorResolvers, onSelectionChange, onExport, onExportRequest }: VisualHtmlEditorProps): React.JSX.Element;

// File: styles.css.d.ts
export {};
